const KEY="null-bloom-fighter-v2";
const options={body:["compact","athletic","heavy"],head:["round","square","long"],face:["bright","stern","strange"],hair:["short","wild","slick","long"],top:["jacket","tee","uniform","armor"],bottom:["pants","shorts","trousers"],footwear:["boots","sneakers","high-tops"],accessory:["gloves","belt","scarf","none"],weapon:["none","baton","blade","hammer"],marking:["none","stripe","stars","paint"],palette:["sunset","electric","candy","night"]};
const defaults=Object.fromEntries(Object.keys(options).map(k=>[k,options[k][0]]));
function validRecipe(value){return value&&typeof value==="object"&&Object.keys(options).every(k=>options[k].includes(value[k]));}
export function mountCreator(root){
 let saved=null;try{saved=JSON.parse(localStorage.getItem(KEY)||"null")}catch{}
 let recipe=validRecipe(saved)?{...saved}:{...defaults};
 const render=()=>{root.innerHTML="<div class=\"creator-head\"><div><h2>FIGHTER CREATOR</h2><p>Modular recipe with validation, autosave, import/export and randomization.</p></div><div class=\"creator-actions\"><button type=\"button\" data-action=\"random\">RANDOMIZE</button><button type=\"button\" data-action=\"save\">SAVE</button><button type=\"button\" data-action=\"export\">EXPORT</button><label class=\"import\">IMPORT<input id=\"creatorImport\" type=\"file\" accept=\"application/json,.json\"></label></div></div><div class=\"creator-grid\">"+Object.entries(options).map(([key,vals])=>"<label>"+key.toUpperCase()+"<select data-key=\""+key+"\">"+vals.map(v=>"<option value=\""+v+"\" "+(recipe[key]===v?"selected":"")+">"+v+"</option>").join("")+"</select></label>").join("")+"</div><pre class=\"recipe-preview\">"+JSON.stringify(recipe,null,2)+"</pre><p class=\"creator-status\" aria-live=\"polite\">Saved locally.</p>";};
 const save=()=>localStorage.setItem(KEY,JSON.stringify(recipe));
 root.innerHTML="";render();
 root.onchange=e=>{if(e.target.matches("select[data-key]")){recipe[e.target.dataset.key]=e.target.value;save();render();}if(e.target.id==="creatorImport"&&e.target.files?.[0]){const fr=new FileReader();fr.onload=()=>{try{const incoming=JSON.parse(fr.result);if(!validRecipe(incoming))throw new Error("invalid");recipe={...incoming};save();render();}catch{const status=root.querySelector(".creator-status");if(status)status.textContent="Import rejected: invalid fighter recipe.";}};fr.readAsText(e.target.files[0]);}};
 root.onclick=e=>{const action=e.target.closest("[data-action]")?.dataset.action;if(action==="random"){for(const k in options)recipe[k]=options[k][Math.floor(Math.random()*options[k].length)];save();render();}else if(action==="save"){save();render();}else if(action==="export"){const blob=new Blob([JSON.stringify(recipe,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="null-bloom-fighter.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}};
}