
import {InputManager} from "./engine/input.js";
import {Fighter} from "./engine/fighter.js";
import {Combat} from "./engine/combat.js";
import {GameLoop} from "./engine/loop.js";
import {MatchState} from "./engine/match.js";
import sol from "../data/characters/sol/character.json" with {type:"json"};
import morrow from "../data/characters/morrow/character.json" with {type:"json"};
import attacks from "../data/characters/example/attacks.json" with {type:"json"};
const defs={sol:{...sol,attacks},morrow:{...morrow,attacks}};
export const bindings={p1:{left:"KeyA",right:"KeyD",jump:"KeyW",crouch:"KeyS",guard:"KeyH",light:"KeyJ",heavy:"KeyK",special:"KeyL",restart:"KeyR"},p2:{left:"ArrowLeft",right:"ArrowRight",jump:"ArrowUp",crouch:"ArrowDown",guard:"Numpad0",light:"Numpad1",heavy:"Numpad2",special:"Numpad3"}};
function read(input,b){return{left:input.held(b.left),right:input.held(b.right),jump:input.consume(b.jump),crouch:input.held(b.crouch),guard:input.held(b.guard)}}
export function createMatch(p1Id="sol",p2Id="morrow"){const p1=new Fighter(defs[p1Id],330,500,1),p2=new Fighter(defs[p2Id],870,500,-1),combat=new Combat(p1,p2),match=new MatchState(p1,p2,{roundTime:99});match.resetRound();return{p1,p2,combat,match};}
export function runMatch(canvas,ui,options={}){const input=new InputManager(),state=createMatch(options.p1Id||"sol",options.p2Id||"morrow"),p1=state.p1,p2=state.p2,combat=state.combat,match=state.match;let paused=false,stopped=false;const cpu=options.mode!=="local";const loop=new GameLoop(()=>{if(stopped||paused){ui(p1,p2,combat,match);return;}if(input.consume(bindings.p1.restart))match.resetMatch();if(!match.finished&&!match.transition){const i=read(input,bindings.p1);if(input.consume(bindings.p1.light))p1.startAttack("light");if(input.consume(bindings.p1.heavy))p1.startAttack("heavy");if(input.consume(bindings.p1.special))p1.startAttack("special");p1.update(i,p2,1/60);let ai;if(cpu){const d=p2.x-p1.x,ad=Math.abs(d),toward=d<0;ai={left:toward&&ad>68,right:!toward&&ad>68,jump:false,crouch:false,guard:false};if(!p2.attack&&!p2.hitstun&&!p2.hitstop){if(p1.attack&&ad<150&&Math.random()<.3)ai.guard=true;else if(ad<92&&Math.random()<.18)p2.startAttack(Math.random()<.7?"light":"heavy");else if(ad>150&&Math.random()<.03)ai.jump=true;}}else{ai=read(input,bindings.p2);if(input.consume(bindings.p2.light))p2.startAttack("light");if(input.consume(bindings.p2.heavy))p2.startAttack("heavy");if(input.consume(bindings.p2.special))p2.startAttack("special");}p2.update(ai,p1,1/60);combat.resolve();combat.endFrame();}match.tick();ui(p1,p2,combat,match);input.endFrame();},()=>{});loop.start();return{...state,stop:()=>{stopped=true;loop.stop();input.destroy();},restart:()=>match.resetMatch(),togglePause:()=>{paused=!paused;match.paused=paused;},isPaused:()=>paused};}
